# Generated by Django 4.0.1 on 2024-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roommember_insession_alter_roommember_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='insession',
        ),
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.CharField(max_length=200),
        ),
    ]
